apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: testsuites.testing.kyma-project.io
spec:
  group: testing.kyma-project.io
  names:
    kind: TestSuite
    plural: testsuites
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            repeat:
              description: Should I repeat every test? Default value will be 1
              format: int64
              type: integer
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - reason
                - message
                type: object
              type: array
            results:
              items:
                properties:
                  conditions:
                    items:
                      properties:
                        message:
                          type: string
                        reason:
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      - status
                      - reason
                      - message
                      type: object
                    type: array
                  id:
                    description: Unique ID of specific test execution. Equivalent
                      to testing Pod name
                    type: string
                  name:
                    description: Test name
                    type: string
                  namespace:
                    type: string
                  retries:
                    description: How many times test was retired
                    format: int64
                    type: integer
                required:
                - name
                - namespace
                - id
                - retries
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
