apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: testsuites.testing.kyma-project.io
spec:
  group: testing.kyma-project.io
  names:
    kind: TestSuite
    plural: testsuites
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            allTestsSelector:
              description: Will run every test if set to true. Default values is false
              type: boolean
            componentsSelector:
              description: Will run every test that depends of any of the component
                listed here
              items:
                type: string
              type: array
            concurrency:
              description: How many tests we want to execute at the same time. Depends
                on cluster size and it's load Default value is 1
              format: int64
              type: integer
            count:
              description: How many times should I run every test? Default value will
                be 1.
              format: int64
              type: integer
            maxRetries:
              description: In case of a failed test, how many times it will be retried.
                If test failed and on retry it succeeded, Test Suite should be marked
                as a succeeded. Default value is 0 - no retries. MaxRetries and Count
                cannot be used mutually.
              format: int64
              type: integer
            testNamesSelector:
              description: You can specify test names explicitly.
              items:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
              type: array
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                - reason
                - message
                type: object
              type: array
            results:
              items:
                properties:
                  conditions:
                    items:
                      properties:
                        message:
                          type: string
                        reason:
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      - status
                      - reason
                      - message
                      type: object
                    type: array
                  id:
                    description: Unique ID of specific test execution. Equivalent
                      to testing Pod name
                    type: string
                  name:
                    description: Test name
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                - id
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
