// Code generated by mockery v1.0.0. DO NOT EDIT.

package automock

import client "sigs.k8s.io/controller-runtime/pkg/client"
import context "context"
import mock "github.com/stretchr/testify/mock"
import runtime "k8s.io/apimachinery/pkg/runtime"
import types "k8s.io/apimachinery/pkg/types"

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, key, obj
func (_m *Reader) Get(ctx context.Context, key types.NamespacedName, obj runtime.Object) error {
	ret := _m.Called(ctx, key, obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.NamespacedName, runtime.Object) error); ok {
		r0 = rf(ctx, key, obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, opts, list
func (_m *Reader) List(ctx context.Context, list runtime.Object, opts ...client.ListOption) error {
	ret := _m.Called(ctx, opts, list)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, runtime.Object, ...client.ListOption) error); ok {
		r0 = rf(ctx, list, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
