---
apiVersion: testing.kyma-project.io/v1alpha1
kind: TestDefinition
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    dependency/kubeless: "true"
    component/service-catalog: "true" # user has a freedom how to define labels
  name: test-example
spec:
  skip: false
  disableConcurrency: false
  timeout: 3m
  description: This is an example TestDefinition resource.
    The test logic is wrapped in the referenced container image.
    A TestDefinition resource will be executed as part of a TestSuite.

    In this example, the test just executes the pwd command,
    but there are no limitations to run any enhanced test logic.
  template:
    spec:
      containers:
        - name: test
          image: alpine:latest
          command:
            - "pwd"
