/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kyma-incubator/octopus/pkg/apis/testing/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterTestSuites implements ClusterTestSuiteInterface
type FakeClusterTestSuites struct {
	Fake *FakeTestingV1alpha1
}

var clustertestsuitesResource = schema.GroupVersionResource{Group: "testing.kyma-project.io", Version: "v1alpha1", Resource: "clustertestsuites"}

var clustertestsuitesKind = schema.GroupVersionKind{Group: "testing.kyma-project.io", Version: "v1alpha1", Kind: "ClusterTestSuite"}

// Get takes name of the clusterTestSuite, and returns the corresponding clusterTestSuite object, and an error if there is any.
func (c *FakeClusterTestSuites) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterTestSuite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clustertestsuitesResource, name), &v1alpha1.ClusterTestSuite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterTestSuite), err
}

// List takes label and field selectors, and returns the list of ClusterTestSuites that match those selectors.
func (c *FakeClusterTestSuites) List(opts v1.ListOptions) (result *v1alpha1.ClusterTestSuiteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clustertestsuitesResource, clustertestsuitesKind, opts), &v1alpha1.ClusterTestSuiteList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterTestSuiteList{ListMeta: obj.(*v1alpha1.ClusterTestSuiteList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterTestSuiteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterTestSuites.
func (c *FakeClusterTestSuites) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clustertestsuitesResource, opts))
}

// Create takes the representation of a clusterTestSuite and creates it.  Returns the server's representation of the clusterTestSuite, and an error, if there is any.
func (c *FakeClusterTestSuites) Create(clusterTestSuite *v1alpha1.ClusterTestSuite) (result *v1alpha1.ClusterTestSuite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clustertestsuitesResource, clusterTestSuite), &v1alpha1.ClusterTestSuite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterTestSuite), err
}

// Update takes the representation of a clusterTestSuite and updates it. Returns the server's representation of the clusterTestSuite, and an error, if there is any.
func (c *FakeClusterTestSuites) Update(clusterTestSuite *v1alpha1.ClusterTestSuite) (result *v1alpha1.ClusterTestSuite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clustertestsuitesResource, clusterTestSuite), &v1alpha1.ClusterTestSuite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterTestSuite), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterTestSuites) UpdateStatus(clusterTestSuite *v1alpha1.ClusterTestSuite) (*v1alpha1.ClusterTestSuite, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clustertestsuitesResource, "status", clusterTestSuite), &v1alpha1.ClusterTestSuite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterTestSuite), err
}

// Delete takes name of the clusterTestSuite and deletes it. Returns an error if one occurs.
func (c *FakeClusterTestSuites) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clustertestsuitesResource, name), &v1alpha1.ClusterTestSuite{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterTestSuites) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clustertestsuitesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterTestSuiteList{})
	return err
}

// Patch applies the patch and returns the patched clusterTestSuite.
func (c *FakeClusterTestSuites) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterTestSuite, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clustertestsuitesResource, name, pt, data, subresources...), &v1alpha1.ClusterTestSuite{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterTestSuite), err
}
