/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kyma-incubator/octopus/pkg/apis/testing/v1alpha1"
	scheme "github.com/kyma-incubator/octopus/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TestDefinitionsGetter has a method to return a TestDefinitionInterface.
// A group's client should implement this interface.
type TestDefinitionsGetter interface {
	TestDefinitions(namespace string) TestDefinitionInterface
}

// TestDefinitionInterface has methods to work with TestDefinition resources.
type TestDefinitionInterface interface {
	Create(*v1alpha1.TestDefinition) (*v1alpha1.TestDefinition, error)
	Update(*v1alpha1.TestDefinition) (*v1alpha1.TestDefinition, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.TestDefinition, error)
	List(opts v1.ListOptions) (*v1alpha1.TestDefinitionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestDefinition, err error)
	TestDefinitionExpansion
}

// testDefinitions implements TestDefinitionInterface
type testDefinitions struct {
	client rest.Interface
	ns     string
}

// newTestDefinitions returns a TestDefinitions
func newTestDefinitions(c *TestingV1alpha1Client, namespace string) *testDefinitions {
	return &testDefinitions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the testDefinition, and returns the corresponding testDefinition object, and an error if there is any.
func (c *testDefinitions) Get(name string, options v1.GetOptions) (result *v1alpha1.TestDefinition, err error) {
	result = &v1alpha1.TestDefinition{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testdefinitions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of TestDefinitions that match those selectors.
func (c *testDefinitions) List(opts v1.ListOptions) (result *v1alpha1.TestDefinitionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.TestDefinitionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("testdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested testDefinitions.
func (c *testDefinitions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("testdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a testDefinition and creates it.  Returns the server's representation of the testDefinition, and an error, if there is any.
func (c *testDefinitions) Create(testDefinition *v1alpha1.TestDefinition) (result *v1alpha1.TestDefinition, err error) {
	result = &v1alpha1.TestDefinition{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("testdefinitions").
		Body(testDefinition).
		Do().
		Into(result)
	return
}

// Update takes the representation of a testDefinition and updates it. Returns the server's representation of the testDefinition, and an error, if there is any.
func (c *testDefinitions) Update(testDefinition *v1alpha1.TestDefinition) (result *v1alpha1.TestDefinition, err error) {
	result = &v1alpha1.TestDefinition{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("testdefinitions").
		Name(testDefinition.Name).
		Body(testDefinition).
		Do().
		Into(result)
	return
}

// Delete takes name of the testDefinition and deletes it. Returns an error if one occurs.
func (c *testDefinitions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testdefinitions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *testDefinitions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("testdefinitions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched testDefinition.
func (c *testDefinitions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.TestDefinition, err error) {
	result = &v1alpha1.TestDefinition{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("testdefinitions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
