/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	testingv1alpha1 "github.com/kyma-incubator/octopus/pkg/apis/testing/v1alpha1"
	versioned "github.com/kyma-incubator/octopus/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kyma-incubator/octopus/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kyma-incubator/octopus/pkg/client/listers/testing/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterTestSuiteInformer provides access to a shared informer and lister for
// ClusterTestSuites.
type ClusterTestSuiteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterTestSuiteLister
}

type clusterTestSuiteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterTestSuiteInformer constructs a new informer for ClusterTestSuite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterTestSuiteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterTestSuiteInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterTestSuiteInformer constructs a new informer for ClusterTestSuite type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterTestSuiteInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TestingV1alpha1().ClusterTestSuites().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TestingV1alpha1().ClusterTestSuites().Watch(options)
			},
		},
		&testingv1alpha1.ClusterTestSuite{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterTestSuiteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterTestSuiteInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterTestSuiteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&testingv1alpha1.ClusterTestSuite{}, f.defaultInformer)
}

func (f *clusterTestSuiteInformer) Lister() v1alpha1.ClusterTestSuiteLister {
	return v1alpha1.NewClusterTestSuiteLister(f.Informer().GetIndexer())
}
